name: Deploy github pages
on:
  push:
    paths:
        - 'docs/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: latest
            - run: cd docs/
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Publish
              uses: actions/upload-pages-artifact@v3
              with:
                path: out/