name: Nightly Release
on:
  push:
    branches: main

jobs:
  build-binary:
    strategy:
      matrix:
        platform:
          - release_for: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: cup
            name: cup-linux-aarch64
            command: build

          - release_for: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: cup
            name: cup-linux-x86_64
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: cross ${{ matrix.platform.command }} --target ${{ matrix.platform.target }}

      - name: Upload CLI
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/debug/${{ matrix.platform.bin }}

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/sergi0g/cup:nightly
          cache-from: type=gha
          cache-to: type=gha,mode=max